config/routes.rb
Rails.application.routes.draw do

  resources :permcls
  resources :permcl_actions
  resources :permissions do
		collection do
			post :user_permissions
		end
  end
  get 'password_resets/new'

  get 'signup', to: 'users#newuser', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :password_resets
  resources :sessions
  resources :users
  resources :homes
  resources :items do
  	collection do
  		get  :scanner
  		post :get_barcode
  		get  :multi_barcode_pdf
  		post :delete_selected
  		match 'search' => 'items#search', via: [:get, :post], as: :search
  	end
  end

  root :to => "homes#index"

end

app/models/permcl.rb
class Permcl < ActiveRecord::Base

  has_many :permissions
	accepts_nested_attributes_for :permissions
	

end

app/models/permcl_action.rb
class PermclAction < ActiveRecord::Base

  has_many :permissions
	accepts_nested_attributes_for :permissions

	def action_value
	end


end

app/controllers/permcls_controller.rb
class PermclsController < ApplicationController
  load_and_authorize_resource
  before_action :set_permcl, only: [:show, :edit, :update, :destroy]

  # GET /permcls
  # GET /permcls.json
  def index
    @permcls = Permcl.all
  end

  # GET /permcls/1
  # GET /permcls/1.json
  def show
  end

  # GET /permcls/new
  def new
    @permcl = Permcl.new
  end

  # GET /permcls/1/edit
  def edit
  end

  # POST /permcls
  # POST /permcls.json
  def create
    @permcl = Permcl.new(permcl_params)

    respond_to do |format|
      if @permcl.save
        format.html { redirect_to @permcl, notice: 'Permcl was successfully created.' }
        format.json { render :show, status: :created, location: @permcl }
      else
        format.html { render :new }
        format.json { render json: @permcl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permcls/1
  # PATCH/PUT /permcls/1.json
  def update
    respond_to do |format|
      if @permcl.update(permcl_params)
        format.html { redirect_to @permcl, notice: 'Permcl was successfully updated.' }
        format.json { render :show, status: :ok, location: @permcl }
      else
        format.html { render :edit }
        format.json { render json: @permcl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permcls/1
  # DELETE /permcls/1.json
  def destroy
    @permcl.destroy
    respond_to do |format|
      format.html { redirect_to permcls_url, notice: 'Permcl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permcl
      @permcl = Permcl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permcl_params
      params.require(:permcl).permit(:systitle, :title)
    end
end

app/helpers/permcls_helper.rb
module PermclsHelper
end

app/views/permcls/_form.html.erb
<%= simple_form_for(@permcl) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :systitle %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/permcls/edit.html.erb
<h1>Editing Permcl</h1>

<%= render 'form' %>

<%= link_to 'Show', @permcl %> |
<%= link_to 'Back', permcls_path %>

app/views/permcls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Permcls</h1>

<table>
  <thead>
    <tr>
      <th>Systitle</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permcls.each do |permcl| %>
      <tr>
        <td><%= permcl.systitle %></td>
        <td><%= permcl.title %></td>
        <td><%= link_to 'Show', permcl %></td>
        <td><%= link_to 'Edit', edit_permcl_path(permcl) %></td>
        <td><%= link_to 'Destroy', permcl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permcl', new_permcl_path %>

app/views/permcls/new.html.erb
<h1>New Permcl</h1>

<%= render 'form' %>

<%= link_to 'Back', permcls_path %>

app/views/permcls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Systitle:</strong>
  <%= @permcl.systitle %>
</p>

<p>
  <strong>Title:</strong>
  <%= @permcl.title %>
</p>

<%= link_to 'Edit', edit_permcl_path(@permcl) %> |
<%= link_to 'Back', permcls_path %>