config/routes.rb
Rails.application.routes.draw do

  resources :permcls
  resources :permcl_actions
  resources :permissions do
		collection do
			post :user_permissions
		end
  end
  get 'password_resets/new'

  get 'signup', to: 'users#newuser', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :password_resets
  resources :sessions
  resources :users
  resources :homes
  resources :items do
  	collection do
  		get  :scanner
  		post :get_barcode
  		get  :multi_barcode_pdf
  		post :delete_selected
  		match 'search' => 'items#search', via: [:get, :post], as: :search
  	end
  end

  root :to => "homes#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Goapp</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<%= csrf_meta_tags %>
</head>
<body>
	<% unless current_page?(login_path)%> <% unless current_page?(sessions_path) %><% unless current_page?(signup_path) %>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Goapp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
        <a class="nav-link" href="<%= root_path %>">Главная</a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(items_path) %>">
        <%= link_to 'Товары', items_path, {:class=> 'nav-link'} %>
      </li>
      <li class="nav-item <%= 'active' if current_page?(users_path) %>">
        <%= link_to 'Пользователи', users_path, {:class=> 'nav-link'} %>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="#">Настройки</a>
      </li>
    </ul>
		<ul class="navbar-nav">
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-search" aria-hidden="true"></i></a>
				<div class="dropdown-menu header-serach" x-placement="bottom-start">
				<form class="form-inline my-2 my-lg-0">
				  <input class="form-control mr-sm-2" type="text" placeholder="Search">
				  <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
				</form>
				</div>
		</li>
		<li class="nav-item  dropdown">
		<% if current_user %>
						<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="fa fa-user-circle" aria-hidden="true"></i> <%= current_user.email %> <span class="caret"></span>
						</a>
						<ul class="dropdown-menu dropdown-user">
								<li class="divider"></li>
								<li><%= link_to "Выйти", logout_path %></li>
						</ul><!-- /.dropdown-user -->
		 <% end %>
				</li>
		</ul>
  </div>
</nav>
<% end %>	<% end %><% end %>

	<main role="main" class="container-fluid">
		 <div class="my-3 p-0">
			  <% unless current_page?(login_path)%> <% unless current_page?(sessions_path) %>
			 <% flash.each do |key, value| %>
 				<%= content_tag(:div, class: "alert alert-#{key} alert-dismissable") do %>
 				<%= value %>
 				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
 				<% end %>
 			<% end %>
				<% end %>	<% end %>

		    <%= yield %>
		 </div>
	</main><!-- content -->

<% unless current_page?(login_path)%> <% unless current_page?(sessions_path) %><% unless current_page?(signup_path) %>
	<footer class=" footer bg-dark text-white mt-5 fixed-bottom">
	  <div class="container-fluid">
		  <div class="row">
	    <ul class="nav justify-content-cente">
		    <li class="nav-item"><%= link_to "Ketago", "http://www.ketago.com", {:target => '_blank', class: 'nav-link' }%></li>
		    <li class="nav-item"><%= link_to "Email", "info@ketago.com", {:target => '_blank', class: 'nav-link' } %></li>
	    </ul>
		  </div>
	  </div>
	</footer>
	<% end %>	<% end %><% end %>
</body>
</html>

app/views/layouts/user_mailer.html.erb
<html>
  <body>
		<p>Здравствуйте</p>
		<%= yield %>

		<p>____________</p>
		<p>C уважением</p>
		<p><%= @app_name %></p>
	</body>
</html>

app/views/layouts/user_mailer.text.erb
Здравствуйте


<%= yield %>

____________
C уважением
<%= @app_name %>